# Generated by Django 4.1 on 2023-11-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="farm_nr",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_farmer",
            field=models.BooleanField(default=False),
        ),
    ]
