# Generated by Django 4.1 on 2023-11-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_address_user_city_user_country_user_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=200),
        ),
    ]
