# Generated by Django 4.1 on 2023-11-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_user_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(null=True, upload_to="images/pfp"),
        ),
    ]
