# Generated by Django 4.1 on 2023-11-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_user_image_user_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avg_rating",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
