# Generated by Django 4.1 on 2023-12-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_user_bio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Farmer"},
        ),
        migrations.AlterField(
            model_name="user",
            name="farm_nr",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="pfp/default.jpg", null=True, upload_to="pfp/"
            ),
        ),
    ]
