# Generated by Django 4.1 on 2023-12-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_user_options_alter_user_farm_nr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="farm_nr",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
