# Generated by Django 4.1 on 2023-12-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_remove_user_farm_nr"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="farm_nr",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
