# Generated by Django 4.1 on 2023-12-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_user_farm_nr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="farm_nr",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
