# Generated by Django 4.1 on 2023-11-23 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_avg_rating"),
        ("reviews", "0002_alter_productreview_rating_farmerreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_set",
                to="products.product",
            ),
        ),
    ]
