# Generated by Django 4.1 on 2023-11-23 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductReview",
        ),
    ]
