# Generated by Django 4.1 on 2023-12-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_delete_productreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=10),
        ),
    ]
