# Generated by Django 4.1 on 2023-12-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_alter_cartitem_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="object_id",
            field=models.CharField(max_length=200),
        ),
    ]
