# Generated by Django 4.1 on 2023-12-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0009_alter_cartitem_object_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="object_pk",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
