# Generated by Django 4.1 on 2023-12-18 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0010_cartitem_object_pk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="object_pk",
        ),
    ]
