# Generated by Django 4.1 on 2023-12-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0011_remove_cartitem_object_pk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
    ]
