# Generated by Django 4.1 on 2023-11-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_remove_cartitem_cart_remove_cartitem_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="avg_rating",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
