# Generated by Django 4.1 on 2023-12-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_remove_product_category_product_categories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="avg_rating",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
