# Generated by Django 4.1 on 2023-12-03 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0008_alter_box_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="farmers",
            field=models.ManyToManyField(
                blank=True, related_name="boxes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
