# Generated by Django 4.1 on 2023-12-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_box_farmers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
