# Generated by Django 4.1 on 2023-12-06 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0010_alter_box_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="confirmed",
            field=models.ManyToManyField(
                blank=True, related_name="confirmed", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
