# Generated by Django 4.1 on 2023-12-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_box_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="fatsecret_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
