# Generated by Django 4.1 on 2023-12-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_remove_box_products_boxitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="boxitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=10),
        ),
    ]
