# Generated by Django 4.1 on 2023-12-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_boxitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[("kg", "Kilogram"), ("piece", "Piece"), ("liter", "Liter")],
                max_length=10,
            ),
        ),
    ]
