# Generated by Django 4.1 on 2023-12-22 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_alter_product_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="fatsecret_id",
        ),
    ]
